version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      #- run:
      #    name: Initialize Keystore File
      #    # mykeystore file convert to base64 string and it's added in environment variable with name KEYSTORE_BASE64.
      #    # and return to the original file state with the "echo $KEYSTORE_BASE64 | base64 --decode > app/mykeystore" command.
      #    command: |
      #      echo $KEYSTORE_BASE64 | base64 --decode > app/mykeystore
      # Set Fabric Api Key with environment variables
      #- run:
      #    name: Initialize Fabric Properties
      #    command: |
      #      echo "apiKey=$FABRIC_API_KEY" >> app/fabric.properties
      #      echo "apiSecret=$FABRIC_API_SECRET" >> app/fabric.properties
      #      cat app/fabric.properties
      #- run:
      #    name: Initialize Keystore File
      #    command: |
      #       echo "signingKeyAlias=$KEYSTORE_KEY_ALIAS" >> keystore.properties
      #       echo "signingKeyAliasPassword=$KEYSTORE_KEY_ALIAS_PASSWORD" >>  keystore.properties
      #       echo "signingStoreFile=$KEYSTORE_STORE_FILE" >>  keystore.properties
      #       echo "signingStorePassword=$KEYSTORE_STORE_PASSWORD" >>  keystore.properties
      #       cat keystore.properties
      - run:
          name: KtLint Format
          command: ./gradlew ktlintFormat
      - run:
          name: Lint
          command: ./gradlew lint
      - store_artifacts:
          path: app/build/outputs/lint
          destination: reports
      - run:
          command: echo "Current Branch:" ${CIRCLE_BRANCH}
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Debug build
          command: ./gradlew assembleDevDebug --no-daemon --stacktrace
      - run:
          name: Release build
          command: ./gradlew assembleDevRelease --no-daemon --stacktrace
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks/
      - run:
          name: Test
          command: ./gradlew testDevDebug
      - store_test_results:
          path: app/build/test-results
      - deploy:
          name: Deploy to Fabric
          command: ./gradlew crashlyticsUploadDistributionDevRelease --stacktrace --debug --no-daemon
workflows:
  version: 2
  workflow:
    jobs:
    - build